ARG DOCKER_IMAGE_BASE=debian:bookworm

FROM ${DOCKER_IMAGE_BASE}

USER root

# Create user
ARG USER=user
ARG UID=1001
ARG GID=1001
RUN groupadd -r -g ${GID} ${USER} && \
    useradd -r -u ${UID} -g ${GID} -m -c "${USER} account" -d /home/${USER} -s /bin/bash ${USER}
