name: ci

on:
  workflow_dispatch:
  push:

env:
  DOCKER_REGISTRY: idelchi
  PLATFORMS: linux/amd64,linux/arm64
  IMAGE: yeet

jobs:
  build:
    # Matrix over TAG instead and have build and devenv for now
    strategy:
      matrix:
        tag:
          - build
          - devenv
    runs-on: ubuntu-24.04
    steps:
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.IMAGE }}
          flavor: |
            latest=false
          tags: ${{ matrix.tag }}

      - name: info
        run: |
          echo "Building image '${{ env.IMAGE }}'"
          echo "tags:"
          echo "${{ steps.meta.outputs.tags }}" | while read -r tag; do
            echo "  - ${tag#${{ env.IMAGE }}:}"
          done

      - uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_REGISTRY }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          file: Dockerfile.${{ matrix.tag }}
          platforms: ${{ env.PLATFORMS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
